export interface Donut {
// Generated by https://quicktype.io
    id:                number;
    ref:               string;
    name:              string;
    calories:          number;
    extras:            string[];
    photo:             string;
    photo_attribution: string;
}


// Generated by https://quicktype.io

export interface Donuts {
    count:   number;
    results: Result[];
}

export interface Result {
    id:   number;
    ref:  string;
    name: string;
}

