// Generated by https://quicktype.io

export interface People {
    complete: Complete[];

}

export interface Complete {
    firstName:  string;
    lastName:   string;
    innovation: string;
    year:       number;
}


